CREATE TABLE `ZebraSurvey` (
  `id`          int(10) unsigned NOT NULL      auto_increment,
  `survey_name` varchar(255)     NOT NULL      default '0',
  `survey_id`   varchar(128)     NOT NULL      default '0',
  `client_id`   varchar(128)     NOT NULL      default '0',
  `created_at`  datetime         NOT NULL      default '0000-00-00 00:00:00',
  `status`      enum('PUBLISHED','INPROGRESS') default 'INPROGRESS',
  `xform`       text                           default NULL,
  PRIMARY KEY  (`id`),
  UNIQUE KEY `survey_id` (`survey_id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ZebraSurveyQuestions` (
  `id`                  int(10) unsigned NOT NULL auto_increment,
  `survey_id`           int(10) unsigned NOT NULL default '0',
  `xform_param_name`    varchar(255)     NOT NULL default '',
  `xform_param_var`     varchar(255)     NOT NULL default '',
  `xform_param_type`    enum('NUMBER','TEXT','DATE','RADIO','DROPDOWN','CHECKBOX','GPS','IMAGE') NOT NULL default 'TEXT',
  `xform_param_options` text             NOT NULL,
  PRIMARY KEY  (`id`),
  KEY `survey_id` (`survey_id`),
  CONSTRAINT `ZebraSurveyQuestions_ibfk_1` FOREIGN KEY (`survey_id`) REFERENCES `ZebraSurvey` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `ZebraSurveySubmissions` (
  `id`                     bigint(20) unsigned NOT NULL auto_increment,
  `survey_id`              int(10) unsigned    NOT NULL ,
  `server_entry_time`      datetime            NOT NULL default '0000-00-00 00:00:00',
  `handset_submit_time`    datetime            NOT NULL default '0000-00-00 00:00:00',
  `handset_id`             varchar(255)        NOT NULL default '',
  `interviewer_id`         varchar(255)        NOT NULL default '',
  `interviewer_name`       varchar(255)        NOT NULL default '',
  `interviewee_name`       varchar(255)        NOT NULL default '',
  `result_hash_deprecated` varchar(128)        NOT NULL default '',
  `result_hash`            varchar(128)        NOT NULL,
  `location`               varchar(70),
  `survey_status`          varchar(20),
  `submission_size`        bigint(15)          NOT NULL default 0,
  `mobile_number`          varchar(19)         NOT NULL default 0,
  `q1` text,
  `q2` text,
  `q3` text,
  `q4` text,
  `q5` text,
  `q6` text,
  `q7` text,
  `q8` text,
  `q9` text,
  `q10` text,
  `q11` text,
  `q12` text,
  `q13` text,
  `q14` text,
  `q15` text,
  `q16` text,
  `q17` text,
  `q18` text,
  `q19` text,
  `q20` text,
  `q21` text,
  `q22` text,
  `q23` text,
  `q24` text,
  `q25` text,
  `q26` text,
  `q27` text,
  `q28` text,
  `q29` text,
  `q30` text,
  `q31` text,
  `q32` text,
  `q33` text,
  `q34` text,
  `q35` text,
  `q36` text,
  `q37` text,
  `q38` text,
  `q39` text,
  `q40` text,
  `q41` text,
  `q42` text,
  `q43` text,
  `q44` text,
  `q45` text,
  `q46` text,
  `q47` text,
  `q48` text,
  `q49` text,
  `q50` text,
  `q51` text,
  `q52` text,
  `q53` text,
  `q54` text,
  `q55` text,
  `q56` text,
  `q57` text,
  `q58` text,
  `q59` text,
  `q60` text,
  `q61` text,
  `q62` text,
  `q63` text,
  `q64` text,
  `q65` text,
  `q66` text,
  `q67` text,
  `q68` text,
  `q69` text,
  `q70` text,
  `q71` text,
  `q72` text,
  `q73` text,
  `q74` text,
  `q75` text,
  `q76` text,
  `q77` text,
  `q78` text,
  `q79` text,
  `q80` text,
  `q81` text,
  `q82` text,
  `q83` text,
  `q84` text,
  `q85` text,
  `q86` text,
  `q87` text,
  `q88` text,
  `q89` text,
  `q90` text,
  `q91` text,
  `q92` text,
  `q93` text,
  `q94` text,
  `q95` text,
  `q96` text,
  `q97` text,
  `q98` text,
  `q99` text,
  `q100` text,
  `q101` text,
  `q102` text,
  `q103` text,
  `q104` text,
  `q105` text,
  `q106` text,
  `q107` text,
  `q108` text,
  `q109` text,
  `q110` text,
  `q111` text,
  `q112` text,
  `q113` text,
  `q114` text,
  `q115` text,
  `q116` text,
  `q117` text,
  `q118` text,
  `q119` text,
  `q120` text,
  `q121` text,
  `q122` text,
  `q123` text,
  `q124` text,
  `q125` text,
  `q126` text,
  `q127` text,
  `q128` text,
  `q129` text,
  `q130` text,
  `q131` text,
  `q132` text,
  `q133` text,
  `q134` text,
  `q135` text,
  `q136` text,
  `q137` text,
  `q138` text,
  `q139` text,
  `q140` text,
  `q141` text,
  `q142` text,
  `q143` text,
  `q144` text,
  `q145` text,
  `q146` text,
  `q147` text,
  `q148` text,
  `q149` text,
  `q150` text,
  `q151` text,
  `q152` text,
  `q153` text,
  `q154` text,
  `q155` text,
  `q156` text,
  `q157` text,
  `q158` text,
  `q159` text,
  `q160` text,
  `q161` text,
  `q162` text,
  `q163` text,
  `q164` text,
  `q165` text,
  `q166` text,
  `q167` text,
  `q168` text,
  `q169` text,
  `q170` text,
  `q171` text,
  `q172` text,
  `q173` text,
  `q174` text,
  `q175` text,
  `q176` text,
  `q177` text,
  `q178` text,
  `q179` text,
  `q180` text,
  `q181` text,
  `q182` text,
  `q183` text,
  `q184` text,
  `q185` text,
  `q186` text,
  `q187` text,
  `q188` text,
  `q189` text,
  `q190` text,
  `q191` text,
  `q192` text,
  `q193` text,
  `q194` text,
  `q195` text,
  `q196` text,
  `q197` text,
  `q198` text,
  `q199` text,
  PRIMARY KEY  (`id`),
  KEY `survey_id` (`survey_id`),
  CONSTRAINT `ZebraSurveySubmissions_ibfk_1` FOREIGN KEY (`survey_id`) REFERENCES `ZebraSurvey` (`id`),
  CONSTRAINT `ZebraSurveySubmissions_uidx_1` UNIQUE(result_hash)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Note that the reference table in thee fk declaration is case sensitive
CREATE TABLE `Answers` (
	`id`                   bigint(20)  unsigned NOT NULL auto_increment,
	`submission_id`        bigint(20)  unsigned NOT NULL, -- Foreign key to ZebraSurveySubmissions. References the zebraSurveySubmmisions.id.
	`question_number`      int(6)      NOT NULL, -- The question number  from the survey that the answer refers to.
	`question_name`        varchar(10) NOT NULL, -- The question number  from the survey that the answer refers to.
	`answer`               text,                 -- The answer to the question.
	`parent`               varchar(128),         -- This is the name of the answer that is the parent of this answer
	`parent_position`      int(4)      unsigned, -- This is the position instance of the parent answer
	`position`             int(4)      unsigned NOT NULL default 0,
PRIMARY KEY (`id`),
KEY `submission_id` (`submission_id`),
CONSTRAINT `ZebraAnswer_ibfk_1` FOREIGN KEY (`submission_id`) REFERENCES `zebrasurveysubmissions` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- Indexes for this table
CREATE INDEX `Submission_id` ON `Answers` (`submission_id`);